### ISSUE TITLE
关于安装问题

### ISSUE THREAD

**Issue by HelloWorldhao** [yidashi/yii2-migration#1]
在配置main.php后，应该还要配置下database的别名。在`command/config/bootstrap.php`中添加
`Yii::setAlias('database', dirname(dirname(__DIR__)) . '/database');`

**Comment by yidashi** [comment]
这个别名不是有吗

**Comment by HelloWorldhao** [comment]
如果单独下载这个模块，没有设置别名的。在DefaultController中45行中，用了`Yii::getAlias();`

**Comment by yidashi** [comment]
确实，谢谢提醒。已修复。
